list:
    @just --list

destroy-builder:
    terraform destroy --target google_compute_region_instance_group_manager.builder_group --target google_compute_instance_template.builder_template

apply-builder:
    terraform apply --target google_compute_instance_template.builder_template --target google_compute_region_instance_group_manager.builder_group

reset-builder:
    terraform destroy --target google_compute_region_instance_group_manager.builder_group --target google_compute_instance_template.builder_template --auto-approve
    terraform apply --target google_compute_instance_template.builder_template --target google_compute_region_instance_group_manager.builder_group --auto-approve