#!/usr/bin/env python3
"""Emit the kjob CRs that would replace the launcher's built-in Job.

A spike, not part of the deploy. It exists so the question "would kjobctl
simplify this?" is answered by artifacts rather than by argument: it reads the
same two files the launcher reads - the profile registry and job.yaml - and
writes what kjob would need to express the same five shapes. Run it and read
the output; the size of that output is most of the answer.

  ./scripts/kjob_spike.py            # writes kueue/spike-kjob/
  ./scripts/kjob_spike.py --summary  # counts only, writes nothing

See docs/kjobctl-evaluation.md for what the output means.
"""

import argparse
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
KUEUE = HERE.parent / "kueue"
LAUNCHER_MANIFEST = KUEUE / "generated/manager/workload/10-launcher.yaml"
JOB_TEMPLATE = KUEUE / "launcher/job.yaml"
OUT_DIR = KUEUE / "spike-kjob"

API = "kjobctl.x-k8s.io/v1alpha1"
NAMESPACE = "buildkite"

# The flags `kjobctl create job` accepts, from `pkg/cmd/create` in
# kubernetes-sigs/kjob v0.1.0. Anything a shape needs that is not in here has
# to be baked into a template, which is why there is one template per shape
# rather than one template and five sets of flags.
CREATE_JOB_FLAGS = frozenset({
    "cmd", "parallelism", "completions", "request", "localqueue", "priority",
    "time", "pod-template-label", "pod-template-annotation",
})


def load_profiles():
    """The launcher's profile registry, read out of the generated ConfigMap."""
    for doc in yaml.safe_load_all(LAUNCHER_MANIFEST.read_text()):
        if not doc or doc.get("kind") != "ConfigMap":
            continue
        if doc["metadata"]["name"] != "tpu-launcher-profiles":
            continue
        return yaml.safe_load(doc["data"]["profiles.yaml"])["profiles"]
    raise SystemExit(f"no tpu-launcher-profiles ConfigMap in {LAUNCHER_MANIFEST}")


def job_spec(profile):
    """job.yaml with the shape substituted, as a kjob JobTemplate body.

    The launcher fills four placeholders. Three of them - chips, topology,
    accelerator label - are properties of the shape, so they can be resolved
    here, once per shape. ${IMAGE} cannot: it is a property of the build, and
    the flag that would supply it does not exist.
    """
    text = JOB_TEMPLATE.read_text()
    for key, value in (
        ("${CHIPS}", str(profile["chips"])),
        ("${TOPOLOGY}", profile["topology"]),
        ("${ACCELERATOR_LABEL}", profile["accelerator_label"]),
    ):
        text = text.replace(key, value)
    spec = yaml.safe_load(text)["spec"]

    # What the launcher's size_fuse_cache() does per run. Static here, because
    # a template is the only place kjob can carry it.
    for volume in spec["template"]["spec"]["volumes"]:
        if volume["name"] == "gke-gcsfuse-cache":
            volume["emptyDir"]["sizeLimit"] = profile["fuse_cache_size"]
    return spec


def render(name, profile):
    template = {
        "apiVersion": API,
        "kind": "JobTemplate",
        "metadata": {"name": f"tpu-{name}", "namespace": NAMESPACE},
        "template": job_spec(profile),
    }
    application_profile = {
        "apiVersion": API,
        "kind": "ApplicationProfile",
        "metadata": {"name": f"tpu-{name}", "namespace": NAMESPACE},
        "spec": {
            "supportedModes": [{
                "name": "Job",
                "template": f"tpu-{name}",
                # localqueue and time are per-shape and could be baked into the
                # template too; they are flags here so the step's invocation
                # shows every value kjob is actually able to carry.
                "requiredFlags": ["cmd", "localqueue", "time"],
            }],
        },
    }
    return template, application_profile


def invocation(name, profile):
    """The step's command line under kjob, for comparison with the launcher's."""
    return (
        f"kubectl kjob create job --profile tpu-{name} \\\n"
        f"  --localqueue {profile['queue']} \\\n"
        f"  --time {profile['max_runtime_seconds']}s \\\n"
        f"  --cmd '<command>'"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary", action="store_true",
                        help="print counts only; write nothing")
    args = parser.parse_args()

    profiles = load_profiles()
    written = []
    total_lines = 0

    if not args.summary:
        OUT_DIR.mkdir(exist_ok=True)

    for name, profile in sorted(profiles.items()):
        template, application_profile = render(name, profile)
        body = (
            f"# Generated by scripts/kjob_spike.py - a spike, not deployed.\n"
            f"#\n"
            f"# The step would run:\n"
            + "".join(f"#   {line}\n" for line in invocation(name, profile).splitlines())
            + f"#\n"
            f"# Blocked: the workload image differs per build and `kjobctl create\n"
            f"# job` has no flag for it, so the image below stays a placeholder\n"
            f"# and this CR cannot be applied as written.\n"
            + yaml.safe_dump(template, sort_keys=False)
            + "---\n"
            + yaml.safe_dump(application_profile, sort_keys=False)
        )
        total_lines += len(body.splitlines())
        written.append(f"tpu-{name}.yaml")
        if not args.summary:
            (OUT_DIR / f"tpu-{name}.yaml").write_text(body)

    launcher_side = len(JOB_TEMPLATE.read_text().splitlines())
    registry_side = sum(
        len(yaml.safe_dump({k: v}).splitlines()) for k, v in profiles.items()
    )

    print(f"shapes:                        {len(profiles)}")
    print(f"kjob CRs emitted:              {len(profiles) * 2} "
          f"({len(profiles)} JobTemplate + {len(profiles)} ApplicationProfile)")
    print(f"kjob YAML lines:               {total_lines}")
    print(f"replaces job.yaml:             {launcher_side} lines")
    print(f"replaces profile registry:     {registry_side} lines")
    print(f"net YAML delta:                "
          f"{total_lines - launcher_side - registry_side:+d} lines")
    if not args.summary:
        print(f"\nwrote {len(written)} files to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
